### ISSUE TITLE
Breaking API change

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#103]
does this affect wbi?
https://www.wikidata.org/wiki/Wikidata:Project_chat#BREAKING_/_SIGNIFICANT_CHANGE:_wbeditentity_response_to_use_standard_JSON_serialization

**Comment by LeMyst** [comment]
At first glance, I would say yes.
I'm gonna work on it this weekend.
Thank you for the report.

**Comment by LeMyst** [comment]
After investigating, the impact seems limited to MediaInfo extension on Commons.
I need to add a check and if the type entity type is 'mediainfo', I use statements instead of claims.
statements don't support 'datatype' field.

I will work on this when I got some time, it will be a busy month for me on a personal side.

**Comment by egils-consulting** [comment]
Good to hear for me because I'm not using mediainfo at all ATM.

**Comment by LeMyst** [comment]
MediaInfo support has been added in v0.12 branch in #175 
After inspecting v0.11 code, I will not add MediaInfo into this branch.
v0.11 don't really support other entity type (Lexeme, Property, etc.) and adding it would force to rewrite a lot of things.
