### ISSUE TITLE
Error when bot parameter is enabled

### ISSUE THREAD

**Issue by jmformenti** [LeMyst/WikibaseIntegrator#299]
When I try to activate `is_bot` parameter I get this error (for example, creating a property):

![Captura de pantalla de 2022-02-27 19-53-19](https://user-images.githubusercontent.com/13070879/155895858-0bedcd14-db99-4c98-aecd-6ffa46c2b840.png)

Honestly, I'm not sure how it affects the `is_bot` parameter, is it a good practice to enable it? What's the difference between turning it on and not turning it on?

**Comment by LeMyst** [comment]
The "is_bot" parameter add the flag "bot" to each edit.
At the same time, if the "is_bot" parameter is set, WBI add an "assertbot" so if you can't use the bot flag to the edit (because you don't have the bot rights on this mediawiki instance), the edit is denied.
Add the bot rights to the account used in WBI if you want to flag the edits.
